### ISSUE TITLE
KeepassXC icon request

### ISSUE THREAD

**Issue by ghost** [snwh/paper-icon-theme#565] opened 2017-05-08 14:36 UTC
### Icon Request

Please provide the following in your request:

- Application name: KeepassX
- Icon=`iconname`: keepassxc
![keepassxc_icon](https://cloud.githubusercontent.com/assets/9356288/25809125/1ab0c050-33da-11e7-8bb5-4d6fb03739df.png)

- Insert/attach a copy of the original icon for reference

**Providing `iconname` is mandatory.**

If you can't find the `iconname`, refer to an app's desktop file, for example: `/usr/share/applications/gimp.desktop`

**Comment by bil-elmoussaoui** [comment] 2017-06-12 15:23
Duplicate of #490

**Closed** 2017-06-13 17:37 UTC
Labels: Status: Duplicate
