### ISSUE TITLE
Enlarged indicators in Pantheon Desktop on elementaryOS

### ISSUE THREAD

**Issue by tristan957** [snwh/paper-icon-theme#284] opened 2016-06-27 18:19 UTC
I'm using elementaryOS and the sound, notifications, and power indicators are very large compared to the network and battery indicators. I'm not sure if this is a desktop issue or an icon theme issue because this theme and the Numix theme have enlarged indicator icons. If this is the case I can resubmit the issue under the Patheon Desktop bug page.
![screenshot from 2016-06-27 13 05 40](https://cloud.githubusercontent.com/assets/11936772/16390648/75374bf2-3c69-11e6-8bc1-58c8f3699668.png)

**Comment by snwh** [comment] 2016-06-29 13:30
Duplicate of #74

**Closed** 2016-07-04 16:26 UTC
Labels: duplicate
