### ISSUE TITLE
Comix

### ISSUE THREAD

**Issue by nicrou** [snwh/paper-icon-theme#493] opened 2017-01-30 22:16 UTC
### Icon Request

Please provide the following in your request:

- Comix
- Icon=`comix`
![comix](https://cloud.githubusercontent.com/assets/23281641/22444146/71f54d40-e74a-11e6-8751-0f16996de0c5.png)

**Comment by bil-elmoussaoui** [comment] 2017-01-30 22:27
Duplicate of #221

**Closed** 2017-02-01 00:48 UTC
Labels: Status: Duplicate
