### ISSUE TITLE
Icon Request: fcitx

### ISSUE THREAD

**Issue by leesah** [snwh/paper-icon-theme#603] opened 2017-08-03 12:43 UTC
### Icon Request

Please provide the following in your request:

- Application name: Fcitx
- Icon=`fcitx`
- Insert/attach a copy of the original icon for reference
![fcitx](https://user-images.githubusercontent.com/504435/28922302-d97cce2a-7859-11e7-9d14-12dea9de8afd.png)

Fcitx is the most popular input method framework among Chinese users.

**Comment by snwh** [comment] 2017-08-03 13:34
duplicate of #119

**Closed by snwh** 2017-08-03 13:34 UTC
