### ISSUE TITLE
Icons for Jetbrains IDEs

### ISSUE THREAD

**Issue by btd1337** [snwh/paper-icon-theme#464] opened 2016-11-20 06:15 UTC
Icons for Jetbrains IDE's are missing.

Example of .desktop
icon=clion

IDE's:
clion
phpstorm
pycharm
intellij
webstorm
rubymine
appcode
datagrip
resharper
resharper-c++

All icons are avaliable here: https://www.jetbrains.com/products.html?fromMenu

**Comment by sonal-keshav** [comment] 2016-12-18 18:21
This is a duplicate of: https://github.com/snwh/paper-icon-theme/issues/262

**Comment by snwh** [comment] 2017-01-02 20:37
@sonal-keshav indeed it is.

**Comment by snwh** [comment] 2017-01-02 20:38
@btd1337 if there are any missing from those listed in #262 feel free to add them as a comment.

**Closed by snwh** 2017-01-02 20:37 UTC
Labels: Status: Duplicate

**Comment by btd1337** [comment] 2017-01-02 20:41
pycharm
rubymine
appcode
datagrip
resharper
resharper-c++
