### ISSUE TITLE
Icon Request : JetBrains PhpStorm

### ISSUE THREAD

**Issue by Typhon0** [snwh/paper-icon-theme#567] opened 2017-05-12 16:39 UTC
### Icon Request

- JetBrains PhpStorm
- Icon=`/opt/phpstorm/bin/phpstorm.png`
- Original icon : 
![phpstorm](https://cloud.githubusercontent.com/assets/10800948/26007715/6931ab54-374a-11e7-896f-96da53c08d14.png)

**Comment by jason-gu** [comment] 2017-05-12 17:00
In case you need this:

[Desktop Entry]
Version=1.0
Type=Application
Name=PhpStorm
Icon=/path/to/PhpStorm/bin/phpstorm.png
Exec="/path/to/PhpStorm/bin/phpstorm.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-phpstorm

**Comment by bil-elmoussaoui** [comment] 2017-06-12 15:05
Duplicate of https://github.com/snwh/paper-icon-theme/issues/262

**Closed** 2017-06-12 15:06 UTC
Labels: Status: Duplicate
