### ISSUE TITLE
Icon on spreading windows.  

### ISSUE THREAD

**Issue by vivekjib** [snwh/paper-icon-theme#347] opened 2016-08-24 19:15 UTC
Whenever I spread all the windows, I see big icons that covers almost full app. You can see in image. I spotted this for terminal and gedit for now.

![screenshot from 2016-08-24 23-49-25](https://cloud.githubusercontent.com/assets/11706579/17944349/0604a38e-6a5d-11e6-833d-8ed83d267b86.png)

**Comment by snwh** [comment] 2016-09-07 15:44
duplicate of #59

**Closed by snwh** 2016-09-07 15:44 UTC

**Comment by vivekjib** [comment] 2016-09-24 14:01
Is there anything I can do about it by myself ? Please let me know.

**Comment by snwh** [comment] 2016-09-24 18:58
@vivekjib not sure.
