### ISSUE TITLE
Jetbrain's CLion icon request

### ISSUE THREAD

**Issue by luzzif** [snwh/paper-icon-theme#559] opened 2017-04-26 19:56 UTC
### Icon Request

- **Application name**: CLion
- **Actual icon location**: by looking at the desktop entry the icon is located in CLion's installation folder, as the property value will be <CLION_INSTALLATION_DIR>/clion.svg. The icon is attached with a PNG format since GitHub doesn't allow an SVG attachment. I'm a newbie about Linux but it seems like if the icon would actually be added to the set one would have to manually edit the app's desktop entry in order for it to get picked up instead of the original one.  

For futher details, here's the actual desktop entry for CLion (with the installation dir substituted by a mock):
```
[Desktop Entry]
Version=1.0
Type=Application
Name=CLion
Icon=<CLION_INSTALLATION_DIR>/bin/clion.svg
Exec="<CLION_INSTALLATION_DIR>/bin/clion.sh" %f
Comment=The Drive to Develop
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-clion
```

![clion](https://cloud.githubusercontent.com/assets/12766550/25453784/856901d2-2aca-11e7-8999-3e2dbff1d43c.png)

**Comment by bil-elmoussaoui** [comment] 2017-06-12 15:05
Duplicate of https://github.com/snwh/paper-icon-theme/issues/262

**Closed** 2017-06-12 15:07 UTC
Labels: Status: Duplicate
