### ISSUE TITLE
PPA Version of Paper theme not appearing (in Mint/Cinnamon)

### ISSUE THREAD

**Issue by Cerealkillerway** [snwh/paper-icon-theme#71] opened 2015-12-03 00:03 UTC
I was using paper icon theme on Elementary Freya but after the latest system update, it is not available anymore (in settings -> tweaks > icons there is no "paper" option anymore;

I tried to uninstall and reinstall but no changes...

Does anyone have the same problem?

**Comment by TimZava** [comment] 2015-12-03 00:07
Confirming present in Ubuntu-Gnome. With most recent (211) Paper is not longer selectable as an icon theme in tweak-tool.

**Comment by Cerealkillerway** [comment] 2015-12-03 00:21
ok for me the problem was that icons were in /usr/share/icons/Paper/Paper
after moving them in /usr/share/icons/Paper everything works again

sudo mv /usr/share/icons/Paper /usr/share/icons/Paper-tmp
sudo mv /usr/share/icons/Paper-tmp/Paper /usr/share/icons/Paper
sudo rm -R /usr/share/icons/Paper-tmp

**Comment by ayhankuru** [comment] 2015-12-03 00:41
@Cerealkillerway Thanks :+1:

**Comment by TimZava** [comment] 2015-12-03 00:47
@Cerealkillerway that fixes it, thanks!

**Comment by zrneely** [comment] 2015-12-03 01:06
@Cerealkillerway I had the same issue and your hotfix worked, thanks.

**Comment by snwh** [comment] 2015-12-03 04:20
Is this after a package update?

**Comment by snwh** [comment] 2015-12-03 04:31
I've been reconfiguring Launchpad packaging so this may be an error with that.

**Comment by logindave** [comment] 2015-12-03 06:15
@Cerealkillerway Thanks!

**Comment by Cerealkillerway** [comment] 2015-12-03 10:00
@snwh yes it happened after package update

**Comment by snwh** [comment] 2015-12-03 15:43
This should be fixed today after the latest package updates.

**Comment by radjuga** [comment] 2015-12-03 17:09
"This is the same issue as #71 try updating your system again"

I already did this. Now I have update after broken one.
And no change.
Just install again and no Paper in CS.

**Comment by snwh** [comment] 2015-12-03 17:12
@radjuga if you uninstall Paper and reinstall it from the PPA you still have issues?

**Comment by radjuga** [comment] 2015-12-03 17:17
Yes, that's right.
It is in /usr/... with no doubled Paper folder, cursor OK but no icons theme in Control Centre.

**Comment by kcaj8** [comment] 2015-12-03 20:05
I can confirm this. I have the same issue with Mint 17.2 Cinnamon.

**Comment by snwh** [comment] 2015-12-03 21:09
@kcaj8 @radjuga where exactly is it installing? Does ```/usr/share/icons/Paper``` exist?

**Comment by kcaj8** [comment] 2015-12-03 21:41
Yes. Everything is at it's place: 

```
me@mybox /usr/share/icons/Paper $ ls -l
total 1111656
drwxr-xr-x 13 root root       4096 Dez  3 22:34 16x16
drwxr-xr-x 12 root root       4096 Dez  3 22:34 16x16@2x
drwxr-xr-x  3 root root       4096 Dez  3 22:34 192x192
drwxr-xr-x  3 root root       4096 Dez  3 22:34 192x192@2x
drwxr-xr-x  4 root root       4096 Dez  3 22:34 22x22
drwxr-xr-x 14 root root       4096 Dez  3 22:34 24x24
drwxr-xr-x 12 root root       4096 Dez  3 22:34 24x24@2x
drwxr-xr-x 12 root root       4096 Dez  3 22:34 32x32
drwxr-xr-x 12 root root       4096 Dez  3 22:34 32x32@2x
drwxr-xr-x 13 root root       4096 Dez  3 22:34 48x48
drwxr-xr-x 12 root root       4096 Dez  3 22:34 48x48@2x
drwxr-xr-x 12 root root       4096 Dez  3 22:34 512x512
drwxr-xr-x 12 root root       4096 Dez  3 22:34 512x512@2x
drwxr-xr-x  3 root root       4096 Dez  3 22:34 64x64
drwxr-xr-x  3 root root       4096 Dez  3 22:34 64x64@2x
drwxr-xr-x  3 root root       4096 Dez  3 22:34 8x8
drwxr-xr-x  3 root root       4096 Dez  3 22:34 8x8@2x
drwxr-xr-x  3 root root       4096 Dez  3 22:34 96x96
drwxr-xr-x  3 root root       4096 Dez  3 22:34 96x96@2x
drwxr-xr-x  2 root root       4096 Dez  3 22:34 cursors
-rw-r--r--  1 root root         38 Dez  3 06:02 cursor.theme
-rw-r--r--  1 root root 1138226228 Dez  3 22:35 icon-theme.cache
-rw-r--r--  1 root root      10214 Dez  3 06:02 index.theme
drwxr-xr-x 11 root root       4096 Dez  3 22:34 symbolic
me@mybox /usr/share/icons/Paper $
```
Why has icon-theme.cache a size of 1.1GB?

**Comment by snwh** [comment] 2015-12-03 21:56
The cache is generated by your system, I've no idea why it's so large.

**Comment by snwh** [comment] 2015-12-03 21:57
If the theme exists in ```/usr/share/icons``` I've no clue why it won't show up.

**Comment by radjuga** [comment] 2015-12-09 10:31
Just have made additional folder in /usr/share/icons as "Pupil" (don't know why this one name :-0 ) and copy all Paper icons theme files/folders there.
Now I have Pupil theme in Control Centre. But Paper doesn't shown.

**Comment by snwh** [comment] 2015-12-09 16:09
If you are still having problems, this may work: remove the PPA and all paper-icon-theme packages and do a clean installation.

    sudo apt-get remove paper-icon-theme
    sudo add-apt-repository -r ppa:snwh/pulp
    sudo apt-get update

And then re-add the ppa and reinstall.

**Comment by radjuga** [comment] 2015-12-09 18:59
Thanks.
Now will do clean install of Mint 17.3.
Hope all will be OK.

**Comment by snwh** [comment] 2015-12-09 19:08
You need not reinstall the entire OS.

**Comment by thegwiz** [comment] 2015-12-09 19:42
Sorry to say, but on Mint 17.3, uninstalling the paper theme, repo, then re-adding and re-installing paper theme still does not seem to work. What I did:

sudo apt-get purge paper-icon-theme
sudo apt-get purge paper-gtk-theme
sudo apt-get autoremove && sudo apt-get clean
Removed the repo from Sources manager, then
sudo apt-get update.

Went to /usr/share/icons/ and made sure there's no Paper folder.

Then,

sudo add-apt-repository ppa:snwh/pulp
sudo apt-get update && sudo apt-get install paper-icon-theme paper-gtk-theme

In the themes window, the Paper icon theme still does not show up. Although, I did notice that Cairo Dock's settings recognized the Paper icon pack in their settings window to change the icon theme of the dock. So maybe a recent change in the theme config itself may be breaking the detection in Mint Theme settings? It's just a rough guess though, I have no clue how theme configs work in Mint.

**Comment by snwh** [comment] 2015-12-10 00:07
You the problems seem to be with those of you using Cinnamon/Mint. I'm not sure what would be going on here, as I don't know how Cinnamon handles themes.

**Comment by snwh** [comment] 2015-12-10 00:25
@thegwiz which version of the Paper icons do you have installed? In my testing with Cinnamon Paper does appear: ![screenshot from 2015-12-09 19-24-07](https://cloud.githubusercontent.com/assets/1217306/11703141/815a9cfc-9eaa-11e5-812e-f0acd7e4b618.png)

**Comment by thegwiz** [comment] 2015-12-10 17:01
@snwh:
paper-icon-theme version is: 1.1+r225~daily~ubuntu14.04.1

**Comment by thegwiz** [comment] 2015-12-11 02:11
@snwh:

I just updated to paper-icon-theme version 1.1+r227~daily~ubuntu14.04.1 but I seem to have th same problem. I can see the cursor theme in the Themes window though.

So I cleaned everything (including removing packages and PPA) and reinstalled the paper-icon-theme, but I still cannot see the icon theme. I think something is specifically wrong with my environment.

@radjuga So how did it go for you? Are you able to get the icon theme to show?

**Comment by snwh** [comment] 2015-12-11 03:58
This is rather puzzling.

**Comment by DaPres** [comment] 2015-12-11 08:05
I just solved this issue in Mint 17.3/Cinnamon by uninstalling other icon themes that contain icons from the Paper theme or mix some of them up. After purging the following icon themes from my system, the Paper icon theme appeared in the theme settings of Cinnamon and I was able to choose it.

Purged icon themes:
ultra-flat-icons
ultra-flat-icons-green
super-flat-remix-icons

**Comment by snwh** [comment] 2015-12-11 14:13
@DaPres that's very odd

**Comment by DaPres** [comment] 2015-12-11 15:21
@snwh This sounds defenitively odd, true that! Here I can provide some additional information:

- I installed the Paper themes from your official ppa: snwh/pulp
- I installed other icon and gtk themes from the following ppa: noobslab/icons and noobslab/themes
- The following link http://gnome-look.org/content/show.php/Super+flat+remix+icon+theme?content=169073 says, that icon set listed there is a mix up of different icon themes.

I do not have a deep understanding of icon theme development and I cannot evaluate what "solutions" may be odd and what are not. But I try my best to provide some further information to you and all the poor guys having the same issues I had.

**Comment by snwh** [comment] 2015-12-11 15:25
@DaPres it's odd, in that I don't see how the presence of other themes would affect other installed themes –they're all pretty self-contained; all a tweak app or setting should be doing is looking in for ```index.theme``` files of each icon theme folder, so why Paper has disappeared I don't know. I would like to know if it is isolated to Paper as an issue.

**Comment by DaPres** [comment] 2015-12-11 16:03
@snwh I just re-installed the icon themes that I purged to be able to see the Paper icon theme in the Cinnamon theme settings dialog and now all installed icon themes are listed, even Paper.

I have absolutely no clue, why my "solution" did the trick. I do not even know, how to reproduce this issue again. Maybe there is something wrong with the icon theme selector from Cinnamon, idk. As a workaround I would recommend all the people with the same problem I had to purge all additional icon themes indluding Paper and then just do a new installation of Paper. In my situation it was not necessary to remove the corresponding PPAs.

I'm happy at least to have a beautiful icon and mouse theme matching your gtk thme. Thanks a lot for your superb job and keep up the hight quality of your work.

cheers

**Comment by thegwiz** [comment] 2015-12-11 20:51
@DaPres Thanks a lot for weighing in. I only ever installed the Paper theme though, so I'm not sure what's going on. I also tried a complete purge-reinstall multiple times without any results. But thank you!

@snwh I will try looking for any open issues about the Cinnamon theme manager. If I find any information, I will let you know. Thank you very much!

**Comment by radjuga** [comment] 2015-12-11 22:24
@thegwiz I'm sorry for delay with reply.
Now I have clean install of Mint Cinnamon 17.3 (not because of Paper Icons issue) and Paper themes will install on tomorrow. So will report what happens on tomorrow.
On 17.2 few days ago I just take all folders and files with Paper Icons and copied to new one folder in /usr/share/icons. Named Pupil (I don't know why). and Paper Icons theme was in Control Center.

**Comment by DaPres** [comment] 2015-12-12 10:29
I made another weird discovery today concerning dissappearing settings possibilities in Cinnamon. After a successful installation and activation of both the Paper icon and the cursor theme, I switched my icon theme to "ultra-flat-icons-green". After that, the Paper icon theme still was selectable in Cinnamon settings manager but now the possibility to choose the Paper cursor theme was not only gone from the settings dialogs but also the used cursor theme fall back to Adwaita or DMZ-Black.

After that I purged Paper icone theme and Paper cursor theme and re-installed them again. And guess what? Yup, the cursor theme was back as an available option, but the icon theme was gone from the settings dialog. That's really a strange behavior!

@thegwiz Thank you for bringing in light in this case by investigating the mint part.

**Comment by radjuga** [comment] 2015-12-12 16:23
Hello to all,

Just made clean install of Paper GTK and Icons themes.
Right after install I have only GTK theme to choose.
And (just for try) I made another folder for cursors and copied all cursors theme items to new folder.
Now I have: Paper GTK, Paper Icons and Paper Cursors (as Paper Cursor name in accordance with new folder name).

**Comment by radjuga** [comment] 2015-12-12 16:50
Not sure for 100%, but looks like it's better to keep icons and cursors themes in different folders for Cinnamon.

**Comment by DaPres** [comment] 2015-12-12 17:04
@radjuga Thank you very much! Your workaround works reproducible in Cinnamon. The following steps are needed to apply this workaround:
1. Open a file browser with administrative rights ("gksu nemo" in Cinnamon)
2. go to /usr/share/icons
3. Create folder "PaperCursor"
4 Navigate to folder "Paper" and move the file "cursor.theme" and the folder "cursors" to the created folder "PaperCursor"
5. Go to theme settings in Cinnamon settings dialog to find the icon theme "Paper" and the cursor theme "PaperCursor"

**Comment by snwh** [comment] 2015-12-12 18:39
FYI: These things you're suggesting will be overwritten when packages are updated.

**Comment by radjuga** [comment] 2015-12-12 18:48
We'll do this after every update.
Or maybe you can prepare two different folders for themes (icons and cursors) for install?

**Comment by DaPres** [comment] 2015-12-12 19:04
@snwh That was absolutely clear to me and I am fine with that. But thank you very mucht for your information. 

Since I do not know, what the recommendations are concerning folder locations of gtk icon and cursor themes, it's difficult to me to make suggestions. But if seperated folders are no problem for other desktop environments, this would be an easy solution. But if it is recommended to have the icon and the cursor themes within the same folder, then I think the Cinnamon team is in charge.

I investigated all icon folders provided by a clean install of Linux Mint and I did not find a single one with a cursor folder in it. So maybe this is not supported in LM or it is not best practice to have icon and cursor themes in the same folder. Either way, I do not want to offend anyone but only help with possible solutions.

**Comment by snwh** [comment] 2015-12-12 20:03
Icon and cursor themes can be in the same folder, this is how GNOME/Adwaita does it and KDE/Oxygen does it.

This seems to be a Cinnamon issue due, in my view, to yet another over-complication of their UI.

**Comment by radjuga** [comment] 2015-12-12 20:06
Cinnamon by default has Adwaita cursor theme only under Adwaita name. No icons.
Maybe this is an issue.
But anyway it is ok for me to update icons theme by hand (and actually for now I use standard cursors theme - DMZ).

**Comment by thegwiz** [comment] 2015-12-12 22:31
@radjuga and @DaPres I can confirm I got it working too! Thanks guys!

@snwh But I like Cinnamon! Not more than Gnome though, I will be switching to a Gnome distro very soon anyway.

Should someone file an issue in the Cinnamon issue tracker?

**Comment by ACinnamonUserInUK** [comment] 2015-12-29 01:22
Hello there

Radjuga's solution worked for me (on Mint 17.3 x64 Cinnamon) - though I had to close the system settings windows and re-open them in order to find the themes within those settings.

*Did* anyone file a bug report in the Cinnamon bugtracker, please?

**Comment by sadalavoaoj** [comment] 2016-02-15 00:38
Hi there,

I am whit the same problem, what @radjuga and @DaPres  said to do it worked. As a workaround but is working now, now i have to update icons/folder manually  always right?


Best regards,

**Comment by lukeb-uk** [comment] 2016-03-23 11:37
I did what @radjuga and @DaPres said to do and then moved the `cursors` folder and `cursor.theme` file back to the Paper folder and then updated the cursor preference. It seems to be working at the moment. I've not restarted the whole OS but I have restarted cinnamon and it's still correct.

**Comment by a-rmz** [comment] 2016-03-30 15:26
I'm running Mint 17.3 x64 Cinnamon, and what worked for me was to copy the theme to a new folder inside the /usr/share/icons folder, and delete the `cursors` and `cursors.theme`, that made the trick. The icons weren't showing on the Theme window, and after that it worked.

**Comment by snwh** [comment] 2016-04-30 00:26
Right, I'm closing this as it's a bug in Cinnamon itself. It appears that Cinnamon fails to distinguish between the Paper cursor theme and the icon theme (how it fails to do what is easily done in other DEs I do not know). I'm not going to split the icon and the cursor theme to workaround this issue.

**Closed by snwh** 2016-04-30 00:26 UTC

**Comment by ACinnamonUserInUK** [comment] 2016-04-30 01:07
Dear all

_If you care about this bug, please file, or augment, a bug report_ here: https://github.com/linuxmint/Cinnamon.

_In the meantime_ - i.e. so long as the bug isn't fixed - _you can do the following_. Update Paper as normal. Then run the script below. Then everything should work - though, perhaps (I am unsure), in order to see updates to Paper you may need to change to a theme other than Paper and then change back again.

```
#!/bin/bash
sudo rm -r -v /usr/share/icons/PaperCursor
sudo mkdir /usr/share/icons/PaperCursor
sudo mv /usr/share/icons/Paper/cursor.theme /usr/share/icons/PaperCursor
sudo mv /usr/share/icons/Paper/cursors /usr/share/icons/PaperCursor
cinnamon-settings themes
exit
```

_Fuller instructions, and caveat_: Create a new '.sh' file (using e.g. Nemo), paste the text below into it (using e.g. Gedit), save it, then set the script to be executable as a program (using e.g. Nemo) then run it after you've updated Paper. I have tested this script only on Mint Cinnamon 17.3. Use the script at your own risk. Note also that the last command of the script, while it will open Cinnamon theme settings (that's all the line does) will throw generate cosmetic errors in the terminal.

**Comment by maxkoryukov** [comment] 2016-05-11 21:25
Thanks, separate folders for icons and cursors works for me!

* Linux Mint 17.3 + Cinnamon
* Paper installed from sources from github ( 6428e60 )

https://github.com/snwh/paper-icon-theme/issues/71#issuecomment-164165256
https://github.com/snwh/paper-icon-theme/issues/71#issuecomment-164168367

**Comment by maxkoryukov** [comment] 2016-05-11 21:31
I spent an hour to find this ticket.. :disappointed:

 @snwh , may be you could add a notice to the readme?
