### ISSUE TITLE
Icon Request: JetBrains CLion

### ISSUE THREAD

**Issue by lakiluki1** [snwh/paper-icon-theme#452] opened 2016-11-05 22:50 UTC
### Icon Request

- JetBrains CLion
- Icon=`clion`
![clion](https://cloud.githubusercontent.com/assets/15184862/20034086/7ae7c86e-a3b2-11e6-9b37-b68f59a11b9d.png)

**Comment by bil-elmoussaoui** [comment] 2017-06-12 15:05
Duplicate of https://github.com/snwh/paper-icon-theme/issues/262

**Closed** 2017-06-12 15:07 UTC
Labels: Request: Addition, Status: Duplicate
